# Generated by Django 3.2.9 on 2021-12-28 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cellar', '0002_delete_usercellar'),
        ('account', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cellars',
            field=models.ManyToManyField(to='cellar.Cellar'),
        ),
    ]
