# Generated by Django 3.2.9 on 2021-12-22 05:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='year_of_birth',
            new_name='birth_year',
        ),
        migrations.AddField(
            model_name='profile',
            name='modified_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_modifiedby', to=settings.AUTH_USER_MODEL),
        ),
    ]
