"""
Cellar admin configuration

Generated by './manage.py startapp cellar'

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of admin and their values, see
https://docs.djangoproject.com/en/3.2/intro/tutorial02/#introducing-the-django-admin
"""

# from django.contrib import admin

# Register your models here.
