"""
Cellar apps configuration

Generated by './manage.py startapp cellar'

For the full list of app and their values, see
https://docs.djangoproject.com/en/3.2/ref/applications/
"""

from django.apps import AppConfig


class CellarConfig(AppConfig):
    """
    Application configuration objects store metadata for an application.

    Attributes
    ----------
    default_auto_field : str
        The implicit primary key type to add to models within this app
    name : str
        This attribute defines which application the configuration applies
    """
    default_auto_field = 'django.db.models.BigAutoField'
    name = 'cellar'
