"""
Cellar models configuration

Generated by './manage.py startapp cellar'

For the full list of app and their values, see
https://docs.djangoproject.com/en/3.2/topics/db/models/
"""
# from django.db import models

# Create your models here.
