"""
Cellar views configuration

Generated by './manage.py startapp cellar'

For the full list of app and their values, see
https://docs.djangoproject.com/en/3.2/topics/http/views/
"""
# from django.shortcuts import render

# Create your views here.
