# Generated by Django 3.2.9 on 2021-11-25 00:19

import cloudinary.models
import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddBottle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateTimeField(default=datetime.datetime(2021, 11, 25, 0, 19, 8, 233932, tzinfo=utc))),
                ('event', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'AddBottle',
            },
        ),
        migrations.CreateModel(
            name='Appellation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'Appellation',
            },
        ),
        migrations.CreateModel(
            name='Bottle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('picture', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
            ],
            options={
                'db_table': 'bottle',
            },
        ),
        migrations.CreateModel(
            name='BottleOutlet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateTimeField(default=datetime.datetime(2021, 11, 25, 0, 19, 8, 237189, tzinfo=utc))),
                ('event', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'BottleOutlet',
            },
        ),
        migrations.CreateModel(
            name='Cellar',
            fields=[
                ('description', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(blank=True, default='Ma Cave', max_length=200)),
                ('uid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Cellar',
            },
        ),
        migrations.CreateModel(
            name='CellarBottle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.IntegerField(blank=True, default=0)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'CellarBottle',
            },
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=200)),
                ('picture', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
            ],
            options={
                'db_table': 'Certification',
            },
        ),
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'Clasification',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'Country',
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=200)),
                ('producer_firstname', models.CharField(blank=True, max_length=250, null=True)),
                ('producer_lastname', models.CharField(blank=True, max_length=250, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=250, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=8, null=True)),
                ('picture', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('website_url', models.CharField(blank=True, max_length=250, null=True)),
                ('facebook_url', models.TextField(blank=True, null=True)),
                ('twitter_url', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Domain',
            },
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'Food',
            },
        ),
        migrations.CreateModel(
            name='GrapeVariety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=200)),
                ('color', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'GrapeVariety',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'Person',
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
                ('purchase_place', models.CharField(max_length=200)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'Purchase',
            },
        ),
        migrations.CreateModel(
            name='TechnicalSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
                ('alcohol_level', models.DecimalField(decimal_places=2, max_digits=4)),
                ('started_apogee', models.IntegerField(blank=True, null=True)),
                ('stopped_apogee', models.IntegerField(blank=True, null=True)),
                ('mark', models.IntegerField(blank=True, default=0)),
                ('tasting_temperature', models.IntegerField(blank=True, default=0)),
                ('storage_temperature', models.IntegerField(blank=True, default=0)),
            ],
            options={
                'db_table': 'TechnicalSheet',
            },
        ),
        migrations.CreateModel(
            name='Volume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=200)),
                ('volume', models.CharField(max_length=10)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
            options={
                'db_table': 'Volume',
            },
        ),
        migrations.CreateModel(
            name='Wine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
                ('cuvee', models.CharField(blank=True, default='', max_length=200)),
                ('terroir', models.CharField(blank=True, default='', max_length=200)),
                ('appellation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cellar.appellation')),
                ('classification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cellar.classification')),
                ('domain', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cellar.domain')),
            ],
            options={
                'db_table': 'Wine',
            },
        ),
        migrations.CreateModel(
            name='WineType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'WineType',
            },
        ),
        migrations.CreateModel(
            name='WineGrapeVariety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
                ('rate', models.IntegerField(blank=True, null=True)),
                ('grape_variety', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cellar.grapevariety')),
                ('wine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cellar.wine')),
            ],
            options={
                'db_table': 'WineGrapeVariety',
            },
        ),
        migrations.AddField(
            model_name='wine',
            name='grape_varieties',
            field=models.ManyToManyField(blank=True, related_name='grape_varieties', through='cellar.WineGrapeVariety', to='cellar.GrapeVariety'),
        ),
        migrations.AddField(
            model_name='wine',
            name='wine_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cellar.winetype'),
        ),
        migrations.CreateModel(
            name='TechnicalSheetFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cellar.food')),
                ('technical_sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cellar.technicalsheet')),
            ],
            options={
                'db_table': 'TechnicalSheetFood',
            },
        ),
        migrations.AddField(
            model_name='technicalsheet',
            name='food_paring',
            field=models.ManyToManyField(blank=True, related_name='food_paring', through='cellar.TechnicalSheetFood', to='cellar.Food'),
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=200)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cellar.country')),
            ],
            options={
                'db_table': 'Region',
            },
        ),
        migrations.CreateModel(
            name='CellarBottleOutlet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.IntegerField(blank=True, default=0)),
                ('bottle_outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cellar.bottleoutlet')),
                ('cellar_bottle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cellar.cellarbottle')),
            ],
            options={
                'db_table': 'CellarBottleOutlet',
            },
        ),
        migrations.CreateModel(
            name='CellarBottleAdd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.IntegerField(blank=True, default=0)),
                ('add_bottle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cellar.addbottle')),
                ('cellar_bottle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cellar.cellarbottle')),
            ],
            options={
                'db_table': 'CellarBottleAdd',
            },
        ),
        migrations.AddField(
            model_name='cellarbottle',
            name='add_bottle',
            field=models.ManyToManyField(blank=True, related_name='add_bottle', through='cellar.CellarBottleAdd', to='cellar.AddBottle'),
        ),
        migrations.AddField(
            model_name='cellarbottle',
            name='bottle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cellar.bottle'),
        ),
        migrations.AddField(
            model_name='cellarbottle',
            name='bottle_outlet',
            field=models.ManyToManyField(blank=True, related_name='bottle_outlet', through='cellar.CellarBottleOutlet', to='cellar.BottleOutlet'),
        ),
        migrations.AddField(
            model_name='cellarbottle',
            name='cellar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cellar.cellar'),
        ),
        migrations.CreateModel(
            name='BottleCertification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
                ('bottle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cellar.bottle')),
                ('certification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cellar.certification')),
            ],
            options={
                'db_table': 'BottleCertification',
            },
        ),
        migrations.AddField(
            model_name='bottle',
            name='certification',
            field=models.ManyToManyField(blank=True, related_name='certification', through='cellar.BottleCertification', to='cellar.Certification'),
        ),
        migrations.AddField(
            model_name='bottle',
            name='volume',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cellar.volume'),
        ),
        migrations.AddField(
            model_name='bottle',
            name='wine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cellar.wine'),
        ),
        migrations.CreateModel(
            name='AppellationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=200)),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cellar.country')),
            ],
            options={
                'db_table': 'AppellationType',
            },
        ),
        migrations.AddField(
            model_name='appellation',
            name='appellation_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cellar.appellationtype'),
        ),
        migrations.AddField(
            model_name='appellation',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cellar.region'),
        ),
        migrations.AddField(
            model_name='addbottle',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cellar.person'),
        ),
        migrations.AddField(
            model_name='addbottle',
            name='purchase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cellar.purchase'),
        ),
    ]
