# Generated by Django 3.2.9 on 2021-12-28 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cellar', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserCellar',
        ),
    ]
