# Generated by Django 3.2.9 on 2021-11-25 00:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cellar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addbottle',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='bottleoutlet',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
