# Generated by Django 3.2.9 on 2021-11-25 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cellar', '0002_auto_20211125_0021'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bottle',
            table='Bottle',
        ),
    ]
