# Generated by Django 3.2.9 on 2021-12-21 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cellar', '0002_rename_uid_cellar_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cellar',
            old_name='id',
            new_name='uid',
        ),
    ]
