# Generated by Django 3.2.9 on 2021-12-28 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cellar', '0002_delete_usercellar'),
    ]

    operations = [
        migrations.AddField(
            model_name='cellar',
            name='bottles',
            field=models.ManyToManyField(through='cellar.CellarBottle', to='cellar.Bottle'),
        ),
    ]
