# Generated by Django 3.2.9 on 2021-12-29 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cellar', '0003_cellar_bottles'),
    ]

    operations = [
        migrations.AddField(
            model_name='winetype',
            name='fra_name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
