# Generated by Django 3.2.9 on 2021-11-25 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cellar', '0003_alter_bottle_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='bottle',
            name='technical_sheet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cellar.technicalsheet'),
        ),
    ]
