# Generated by Django 3.2.9 on 2021-12-29 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cellar', '0004_winetype_fra_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bottle',
            name='technical_sheet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cellar.technicalsheet'),
        ),
    ]
