# Generated by Django 3.2.9 on 2021-12-22 05:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cellar', '0004_auto_20211221_0754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addbottle',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addbottle_createdby', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='appellation',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appellation_createdby', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='appellationtype',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appellationtype_createdby', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bottle',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bottle_createdby', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bottlecertification',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bottlecertification_createdby', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bottleoutlet',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bottleoutlet_createdby', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cellar',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cellar_createdby', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cellarbottle',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cellarbottle_createdby', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cellarbottleadd',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cellarbottleadd_createdby', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cellarbottleoutlet',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cellarbottleoutlet_createdby', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='certification',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certification_createdby', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='classification',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classification_createdby', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='country',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='country_createdby', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='domain',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='domain_createdby', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='food',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='food_createdby', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='grapevariety',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grapevariety_createdby', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='person',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='person_createdby', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_createdby', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='region',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='region_createdby', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='technicalsheet',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='technicalsheet_createdby', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='technicalsheetfood',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='technicalsheetfood_createdby', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usercellar',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usercellar_createdby', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='volume',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='volume_createdby', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='wine',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wine_createdby', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='winegrapevariety',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winegrapevariety_createdby', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='winetype',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winetype_createdby', to=settings.AUTH_USER_MODEL),
        ),
    ]
