# Generated by Django 3.2.9 on 2021-12-18 06:26

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cellar', '0004_bottle_technical_sheet'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='picture',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
