# Generated by Django 3.2.9 on 2021-12-29 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cellar', '0005_alter_bottle_technical_sheet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bottle',
            name='technical_sheet',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cellar.technicalsheet'),
        ),
    ]
